name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: cd functions/ && npm install

      - name: Set up Google Cloud credentials
        run: echo $DIALOGFLOW_KEY > functions/dialogflow_key.json  

      - name: Upload Dialogflow Key as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dialogflow_key
          path: functions/dialogflow_key.json
          
      - name: deploy to production
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          