name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: cd functions/ && npm install && echo "${{ secrets.DIALOGFLOW_KEY }}" > dialogflow_key.json
      # - name: Write dialogflow_key.json
      #   run: echo "${{ secrets.DIALOGFLOW_KEY }}" > dialogflow_key.json

      - name: deploy to production
        uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          